-- Advent of Code 2021, day 08, part 1 (golf)
--c=0 for l in io.lines() do for w in l:match("|.+"):gmatch("%S+") do c=c+(({0,2,3,4,0,0,7})[#w]>0 and 1 or 0) end end print(c)
--c=0 for l in io.lines() do l:match("|.+"):gsub("%S+",function(w) c=c+(({0,2,3,4,0,0,7})[#w]>0 and 1 or 0) end) end print(c)
--c=0 for l in io.lines() do l:match("|.+"):gsub("%S+",function(w) c=c+(("2347"):find(#w) and 1 or 0) end) end print(c)
--c=0 for l in io.lines()do l:match("|.+"):gsub("%S+",function(w)if("2347"):find(#w)then c=c+1 end end)end print(c)
  c=0 for l in io.lines()do l:match("|.+"):gsub("%S+",function(w)c=c+(("2347"):find(#w) and 1 or 0)end)end print(c)
